remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Tobias Gray
description: A writer of the weird, the wonderful, and the wonderfully weird. 
